# Generated by Django 2.1.5 on 2021-02-17 02:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='room',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='significant_feature',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
