# Generated by Django 2.1.5 on 2021-02-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip',
        ),
    ]
