# Generated by Django 2.1.5 on 2021-02-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210210_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='room',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
