# Generated by Django 2.1.5 on 2021-02-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20210212_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='stay',
            field=models.IntegerField(default=0),
        ),
    ]
